language: node_js
rvm:
 - 11
 - node
services:
  postgresql

jobs:
  include:
    - stage: "Server Tests"
    install: ./scripts/initDb.js test
    - before_script: echo "Running tests against $(node -v) ..."
      node_js:
        - "8"
      script: yarn test
      - before_script: echo "Running tests against $(node -v) ..."
      node_js:
        - "11"
      script: yarn test
    - stage: "Client Tests"
      before_script: cd client
      script: yarn install && yarn test