language: node_js
node_js:
  - "8"
  - "10"
  - "11"
services:
  postgresql
jobs:
  include:
    - stage: "Server Tests"
    - before_script:
        - ./scripts/initDb.js test
        - echo "Running tests against $(node -v) ..."
      script: yarn test
    - stage: "Client Tests"
      before_script: cd client
      script: yarn install && yarn test