language: node_js
node_js:
  - "8"
  - "10"
  - "11"
services:
  postgresql
before_script:
  - ./scripts/initDb.js test
jobs:
  include:
    - stage: "Client Tests"
      node_js: "11"
      before_script: cd client
      script: yarn install && yarn test